version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    container_name: walheim
    restart: always
    environment:
      - PORT=2456
      - NAME="Valheim Docker Server yay"
      - PASSWORD="yes you should change that, dont blame me if you dont"
      - PUBLIC=1
      - TZ=Europe/Berlin
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="0 3 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - UPDATE_ON_STARTUP=1
      - WEBHOOK_URL=https://discord.com/api/webhooks/nope-not-working-please-change-this
      - WEBHOOK_BROADCAST_MESSAGE='Hello there'
      - WEBHOOK_UPDATING_MESSAGE='Doing Updates, please stand by.'
      - WEBHOOK_UPDATE_SUCCESSFUL_MESSAGE='Update successful.'
      - WEBHOOK_UPDATE_FAILED_MESSAGE='Oh no! Update failed.'
      - WEBHOOK_STARTING_MESSAGE='Server is starting...'
      - WEBHOOK_START_SUCCESSFUL_MESSAGE='Server is running now.'
      - WEBHOOK_START_FAILED_MESSAGE='Thats sad, server start failed.'
      - WEBHOOK_STOPPING_MESSAGE='Going to take a nap, maybe I'll be back later.'
      - WEBHOOK_STOP_SUCCESSFUL_MESSAGE='Server stopped.'
      - WEBHOOK_STOP_FAILED_MESSAGE='Server can't stop, going to crash now.'
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./valheim/server:/home/steam/valheim
    - ./valheim/backups:/home/steam/backups
