version: "3"
services:
    traccar:
        image: traccar/traccar
        container_name: traccar
        restart: always
        volumes:
            - ./data/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
            - ./data/log:/opt/traccar/logs:rw
            - ./data/db:/opt/traccar/data:rw
        ports:
            - "8082:8082"
